# ------------------------
# Services
# ------------------------ 
services:
    # ------------------------
    # Postgres
    # ------------------------
    postgres:
        image: postgres:15-alpine
        container_name: postgres_db5
        hostname: postgres_db5
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: orders_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres" ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - shared

    pgweb:
        image: sosedoff/pgweb
        container_name: pgweb5
        hostname: pgweb5
        restart: always
        ports:
          - "5050:8081"
        environment:
            PGWEB_DATABASE_URL: postgres://user:password@postgres:5432/orders_db?sslmode=disable
        depends_on:
          - postgres
        networks:
          - shared

  # ------------------------
  # Cassandra
  # ------------------------
    cassandra:
        image: cassandra:5.0
        container_name: cassandra5
        environment:
            - CASSANDRA_CLUSTER_NAME=OrderCluster
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_RACK=rack1
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_NUM_TOKENS=256
        ports:
            - "9042:9042"  # CQL port
            - "7199:7199"  # JMX port
            - "9160:9160"  # Thrift port
        volumes:
            - cassandra_data:/var/lib/cassandra
        healthcheck:
          test: ["CMD-SHELL", "cqlsh -e 'describe cluster'"]
          interval: 30s
          timeout: 10s
          retries: 10
          start_period: 60s
        networks:
            - shared

    # ------------------------
    # Kafka
    # ------------------------
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.0
        container_name: zookeeper5
        hostname: zookeeper5
        ports:
            - "2181:2181"
        environment:
            # Port on which Zookeeper listens for connections from Kafka
            ZOOKEEPER_CLIENT_PORT: 2181
            # Heartbeat
            ZOOKEEPER_TICK_TIME: 2000
        healthcheck:
            test: [ "CMD", "nc", "-z", "localhost", "2181" ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - shared
        volumes:
            - zookeeper_data:/var/lib/zookeeper/data
            - zookeeper_logs:/var/lib/zookeeper/log

    kafka:
        image: confluentinc/cp-kafka:7.5.0
        container_name: kafka5
        hostname: kafka5
        ports:
            - "9092:9092"
        environment:
            # Unique identifier of this broker in the cluster
            KAFKA_BROKER_ID: 1
            # Zookeeper address for connection. zookeeper here is the service name in the network.
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            # Define all types of connections (entry points) to kafka: <name:protocol>
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INNER:PLAINTEXT,EXTERNAL:PLAINTEXT
            # Which real ports Kafka physically listens for connections on.
            KAFKA_LISTENERS: INNER://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
            # Which addresses Kafka reports to clients after connection
            # ${KAFKA_HOST_INTERNAL}:${KAFKA_PORT_INTERNAL} - .net applications will connect here. {KAFKA_ADVERTISED_HOST}:${KAFKA_ADVERTISED_PORT} - from PC (not from network)
            KAFKA_ADVERTISED_LISTENERS: INNER://kafka:29092,EXTERNAL://localhost:9092
            # Which listener to use for communication between Kafka brokers (now it's 1, so doesn't matter).
            KAFKA_INTER_BROKER_LISTENER_NAME: INNER
            # Service topic __consumer_offsets stores consumer reading positions. How many replicas of this topic to create.
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            # Default number of partitions for created topics
            KAFKA_NUM_PARTITIONS: 3
        depends_on:
            zookeeper:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:29092" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - shared
        volumes:
            - kafka_data:/var/lib/kafka/data

    kafka-ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka-ui5
        hostname: kafka-ui5
        restart: always
        ports:
            - "8080:8080"
        environment:
            # Parameter KAFKA_CLUSTERS_0_NAME - Cluster name in UI
            KAFKA_CLUSTERS_0_NAME: local-kafka-cluster
            # Parameter KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS - Kafka broker address
            # Uses internal address: service_name:port, which listens on INNER listener
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
        depends_on:
            kafka:
                condition: service_healthy
        networks:
            - shared

# ------------------------
# Volumes
# ------------------------ 
volumes:
  postgres_data:
  cassandra_data:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:

# ------------------------
# Networks
# ------------------------ 
networks:
    shared:
        driver: bridge
        name: shared-network
